const SUPABASE_URL='https://ihottewckpwpwqzpxusl.supabase.co';
const SUPABASE_KEY='sb_publishable_K7aTp6hLR_Pcpn7UGvArLg_DEgBjlH4';
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);

let currentUser=null,currentAccess=null;
let trips=[],personale=[],vehicles=[],months=[];
const comuni=['Sede','Agrate Conturbia','Arona','Baveno','Biandrate','Boca','Bogogno','Bolzano Novarese','Borgo Ticino','Borgomanero','Briga Novarese','Cameri','Carpignano Sesia','Casalbeltrame','Casaleggio Novara','Casalino','Casalvolone','Castelletto Sopra Ticino','Cavaglio d’Agogna','Cavallirio','Cerano','Colazza','Comignago','Cressa','Cureggio','Divignano','Dormelletto','Fara Novarese','Fontaneto d’Agogna','Galliate','Garbagna Novarese','Gargallo','Gattico-Veruno','Ghemme','Gozzano','Granozzo con Monticello','Invorio','Landiona','Lesa','Maggiora','Mandello Vitta','Marano Ticino','Massino Visconti','Meina','Mezzomerico','Miasino','Momo','Nebbiuno','Nibbiola','Novara','Oleggio','Oleggio Castello','Orta San Giulio','Paruzzaro','Pella','Pettenasco','Pisano','Pogno','Pombia','Prato Sesia','Recetto','Romagnano Sesia','Romentino','San Maurizio d’Opaglio','San Nazzaro Sesia','San Pietro Mosezzo','Sillavengo','Sizzano','Soriso','Sozzago','Suno','Terdobbiate','Trecate','Vaprio d’Agogna','Varallo Pombia','Vespolate','Vicolungo','Vinzaglio','Borgosesia','Gattinara','Santhià','Vercelli','Cannobio','Domodossola','Gravellona Toce','Omegna','Stresa','Verbania'];
const serviceTypes=['Emergenza / Urgenza','Dimissione','Trasferimento','Visita','Trasporto semplice','Assistenza manifestazione','Servizio sociale','Altro'];
const richiedenti=['C.O NOVARA','PRIVATO','RSA','COMUNE',"SOCIETA' SPORTIVA"];
const tipiLuogoCarico=['Casa','Scuola','Impianto sportivo','Altro'];
const metodiPagamento=['Bonifico','Bonifico istantaneo','Contante','POS'];
const ospedali=['','Ospedale SS. Trinità - Borgomanero','Ospedale Maggiore della Carità - Novara','Ospedale Santissima Trinità - Arona','Ospedale Castelli - Verbania','Ospedale San Biagio - Domodossola','Ospedale degli Infermi - Biella','Ospedale Sant’Andrea - Vercelli','Ospedale Cardinal Massaia - Asti','Ospedale Santa Croce e Carle - Cuneo','Ospedale Mauriziano - Torino','Ospedale Molinette - Torino','Ospedale San Luigi Gonzaga - Orbassano','Ospedale Maggiore Policlinico - Milano','Ospedale Niguarda - Milano','Ospedale San Raffaele - Milano','Humanitas - Rozzano','Ospedale di Circolo - Varese','Ospedale Sant’Anna - Como','Ospedale Papa Giovanni XXIII - Bergamo','Spedali Civili - Brescia','Policlinico San Matteo - Pavia','Ospedale Santa Chiara - Trento','AOU Verona','AOU Padova','Ospedale Maggiore - Bologna','AOU Careggi - Firenze','AOU Pisana - Pisa','Ospedale di Livorno','Ospedale Misericordia - Grosseto'];

const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const iso=d=>{const x=new Date(d);const off=x.getTimezoneOffset();return new Date(x.getTime()-off*60000).toISOString().slice(0,10)};
const ymNow=()=>iso(new Date()).slice(0,7);
const money=n=>'€ '+Number(n||0).toLocaleString('it-IT',{minimumFractionDigits:2,maximumFractionDigits:2});
const role=()=>currentAccess?.ruolo||'';
const canEdit=()=>['AMMINISTRATORE','CENTRALINO'].includes(role());
const isAdmin=()=>role()==='AMMINISTRATORE';
const personName=badge=>personale.find(p=>p.badge===badge)?.nome_completo||badge||'';
const vehicleName=code=>{const v=vehicles.find(x=>x.codice===code);if(!v)return code||'';return v.tipologia==='AMBULANZA'?'Ambulanza '+v.codice:'Trasporto semplice '+v.codice};

function showError(e,prefix='Errore'){console.error(e);alert(prefix+': '+(e?.message||e||'operazione non riuscita'))}
function setBusy(on,msg='Caricamento...'){const el=$('busyOverlay');if(!el)return;el.style.display=on?'flex':'none';$('busyText').textContent=msg}
async function login(e){e?.preventDefault();const email=$('loginEmail').value.trim(),password=$('loginPassword').value;$('loginError').textContent='';const {error}=await sb.auth.signInWithPassword({email,password});if(error){$('loginError').textContent='Accesso non riuscito. Controlla email e password.';return}await bootstrap()}
async function logout(){await sb.auth.signOut();location.reload()}
async function bootstrap(){
  setBusy(true,'Verifica accesso...');
  const {data:{user},error}=await sb.auth.getUser();
  if(error||!user){setBusy(false);$('loginOverlay').style.display='flex';return}
  currentUser=user;
  const {data:acc,error:ae}=await sb.from('accessi_app').select('user_id,nome,ruolo,attivo').eq('user_id',user.id).eq('attivo',true).maybeSingle();
  if(ae||!acc||!['AMMINISTRATORE','CENTRALINO','CONSULTAZIONE'].includes(acc.ruolo)){await sb.auth.signOut();setBusy(false);$('loginOverlay').style.display='flex';$('loginError').textContent='Utente non abilitato al Registro Viaggi.';return}
  currentAccess=acc;$('loginOverlay').style.display='none';$('who').textContent=(acc.nome||user.email)+' · '+acc.ruolo;applyRoleUi();
  try{await loadResources();await loadData();initStaticSelects();resetForm();showView(role()==='CONSULTAZIONE'?'archivio':'nuovo')}catch(e){showError(e,'Caricamento iniziale')}setBusy(false)
}
function applyRoleUi(){const edit=canEdit(),admin=isAdmin();document.querySelector('[data-view="nuovo"]').style.display=edit?'block':'none';document.querySelector('[data-view="impostazioni"]').style.display=admin?'block':'none';$('tripForm').querySelectorAll('input,select,textarea,button').forEach(x=>x.disabled=!edit);$('logoutBtn').style.display='inline-block'}
async function loadResources(){
  const [p,v]=await Promise.all([
    sb.from('personale').select('badge,nome_completo,autista,capo_servizio,soccorritore,secondo_soccorritore,attivo,stato_anagrafico').eq('attivo',true).eq('stato_anagrafico','ATTIVO').order('badge'),
    sb.from('mezzi').select('codice,tipologia,targa,attivo').eq('attivo',true).order('codice')
  ]);if(p.error)throw p.error;if(v.error)throw v.error;personale=p.data||[];vehicles=v.data||[]
}
async function loadData(){
  const [t,m]=await Promise.all([sb.from('registro_viaggi').select('*').order('data',{ascending:false}).order('numero',{ascending:false}),sb.from('registro_viaggi_mesi').select('*').order('mese',{ascending:false})]);
  if(t.error)throw t.error;if(m.error)throw m.error;trips=t.data||[];months=m.data||[];renderAll()
}
function initStaticSelects(){
  $('tipoServizio').innerHTML='<option value="">Seleziona tipo servizio</option>'+serviceTypes.map(v=>'<option>'+esc(v)+'</option>').join('');
  $('richiedenteServizio').innerHTML='<option value="">Seleziona richiedente</option>'+richiedenti.map(v=>'<option>'+esc(v)+'</option>').join('');
  $('tipoLuogoCarico').innerHTML='<option value="">Seleziona tipo luogo</option>'+tipiLuogoCarico.map(v=>'<option>'+esc(v)+'</option>').join('');
  $('metodoPagamento').innerHTML='<option value="">Seleziona metodo</option>'+metodiPagamento.map(v=>'<option>'+esc(v)+'</option>').join('');
  $('ospedale').innerHTML=ospedali.map(v=>'<option value="'+esc(v)+'">'+esc(v||'Nessun ospedale/clinica')+'</option>').join('');
  const vo=vehicles.map(v=>'<option value="'+esc(v.codice)+'">'+esc(vehicleName(v.codice))+'</option>').join('');$('mezzo').innerHTML='<option value="">Seleziona mezzo</option>'+vo;$('fMezzo').innerHTML='<option value="">Tutti i mezzi</option>'+vo;
  fillRoles();renderComboList('partenza','');renderComboList('luogoCarico','');renderComboList('destinazione','');renderEquipaggi()
}
function fillRoles(){const fill=(id,filter,label)=>{$(id).innerHTML='<option value="">Seleziona '+label+'</option>'+personale.filter(filter).map(p=>'<option value="'+esc(p.badge)+'">'+esc(p.badge+' · '+p.nome_completo)+'</option>').join('')};fill('autista',p=>p.autista,'autista');fill('capo',p=>p.capo_servizio,'capo equipaggio');fill('soc1',p=>p.soccorritore,'soccorritore');fill('soc2',p=>p.secondo_soccorritore||p.soccorritore,'secondo soccorritore')}
function renderEquipaggi(){const rows=personale.map(p=>'<tr><td><b>'+esc(p.badge)+'</b></td><td>'+esc(p.nome_completo)+'</td><td>'+(p.autista?'✓':'')+'</td><td>'+(p.capo_servizio?'✓':'')+'</td><td>'+(p.soccorritore?'✓':'')+'</td><td>'+(p.secondo_soccorritore?'✓':'')+'</td></tr>').join('');$('equipaggi').querySelector('.panel').innerHTML='<h2>Volontari e qualifiche sincronizzati</h2><div class="notice">Elenco letto direttamente dal database del personale. Le tendine del viaggio si aggiornano in base alle qualifiche attive.</div><div class="tablewrap"><table style="min-width:700px"><thead><tr><th>Badge</th><th>Volontario</th><th>Autista</th><th>Capo equipaggio</th><th>Soccorritore</th><th>Secondo soccorritore</th></tr></thead><tbody>'+rows+'</tbody></table></div>'}
function renderComboList(id,filter){const list=$(id+'List');if(!list)return;const q=(filter||'').toLowerCase();const vals=comuni.filter(v=>!q||v.toLowerCase().includes(q));list.innerHTML=vals.map(v=>'<div onclick="selectCombo(\''+id+'\',\''+v.replace(/'/g,"\\'")+'\')">'+esc(v)+'</div>').join('')}
function toggleCombo(id){document.querySelectorAll('.combo-list').forEach(x=>{if(x.id!==id+'List')x.classList.remove('open')});renderComboList(id,$(id).value);$(id+'List').classList.toggle('open')}
function selectCombo(id,value){$(id).value=value;$(id+'List').classList.remove('open')}
['partenza','luogoCarico','destinazione'].forEach(id=>document.addEventListener('input',e=>{if(e.target.id===id){renderComboList(id,e.target.value);$(id+'List').classList.add('open')}}));document.addEventListener('click',e=>{if(!e.target.closest('.combo'))document.querySelectorAll('.combo-list').forEach(x=>x.classList.remove('open'))});
function showView(id){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');document.querySelectorAll('.navbtn').forEach(b=>b.classList.toggle('active',b.dataset.view===id));if(id==='nuovo'&&!$('editId').value)resetForm();if(id==='impostazioni'&&isAdmin())loadAdminTools();window.scrollTo(0,0)}
document.querySelectorAll('.navbtn').forEach(b=>b.onclick=()=>showView(b.dataset.view));
function syncVehicle(){const v=vehicles.find(x=>x.codice===$('mezzo').value);$('targa').value=v?.targa||''}
function calcKm(){const i=Number($('kmIniziali').value),f=Number($('kmFinali').value);$('km').value=(Number.isFinite(i)&&Number.isFinite(f)&&f>=i)?f-i:''}
function syncPaziente118(){const has=($('scheda118').value||'').trim()!=='';['nomePaziente','cognomePaziente'].forEach(id=>{const el=$(id);if(has){el.value='';el.disabled=true;el.style.background='#eef1f5';el.placeholder='Disattivato: presente scheda 118'}else{el.disabled=false;el.style.background='white';el.placeholder=id==='nomePaziente'?'Nome':'Cognome'}})}
$('mezzo').addEventListener('change',syncVehicle);$('kmIniziali').addEventListener('input',calcKm);$('kmFinali').addEventListener('input',calcKm);$('scheda118').addEventListener('input',syncPaziente118);
$('tipoLuogoCarico').addEventListener('change',()=>{const a=$('tipoLuogoCarico').value==='Altro';$('altroLuogoWrap').style.display=a?'flex':'none';if(!a)$('altroLuogoCarico').value=''});
$('tipoServizio').addEventListener('change',()=>{if($('tipoServizio').value==='Emergenza / Urgenza')$('scheda118').setAttribute('required','required');else $('scheda118').removeAttribute('required')});
function resetForm(){if(!canEdit())return;$('tripForm').reset();$('editId').value='';$('numero').value='Automatico';$('data').value=iso(new Date());$('formTitle').textContent='Nuovo viaggio';$('km').value='';$('targa').value='';$('altroLuogoWrap').style.display='none';syncPaziente118()}
function formPayload(){
  const badges=[$('autista').value,$('capo').value,$('soc1').value,$('soc2').value].filter(Boolean);if(new Set(badges).size!==badges.length)throw new Error('Lo stesso volontario non può essere inserito in più ruoli');
  const ki=Number($('kmIniziali').value),kf=Number($('kmFinali').value);if(!Number.isFinite(ki)||!Number.isFinite(kf)||kf<ki)throw new Error('I km finali devono essere uguali o superiori ai km iniziali');
  if($('tipoServizio').value==='Emergenza / Urgenza'&&!$('scheda118').value.trim())throw new Error('Per Emergenza / Urgenza è obbligatorio il N° scheda 118');
  return {data:$('data').value,tipo_servizio:$('tipoServizio').value,richiedente_servizio:$('richiedenteServizio').value,scheda_118:$('scheda118').value.trim()||null,nome_paziente:$('scheda118').value.trim()?null:($('nomePaziente').value.trim()||null),cognome_paziente:$('scheda118').value.trim()?null:($('cognomePaziente').value.trim()||null),mezzo:$('mezzo').value,targa:$('targa').value,km_iniziali:ki,km_finali:kf,ora_partenza:$('oraPartenza').value||null,luogo_partenza:$('partenza').value.trim()||null,ora_destinazione:$('oraDest').value||null,luogo_carico:$('luogoCarico').value.trim()||null,tipo_luogo_carico:$('tipoLuogoCarico').value||null,altro_luogo_carico:$('altroLuogoCarico').value.trim()||null,luogo_fine:$('destinazione').value.trim()||null,ospedale_clinica:$('ospedale').value||null,ora_fine:$('oraFine').value||null,metodo_pagamento:$('metodoPagamento').value||null,numero_ricevuta:$('numeroRicevuta').value.trim()||null,importo:Number($('importo').value||0),autista_badge:$('autista').value||null,capo_badge:$('capo').value||null,soccorritore_1_badge:$('soc1').value||null,soccorritore_2_badge:$('soc2').value||null,note:$('note').value.trim()||null}
}
$('tripForm').addEventListener('submit',async e=>{e.preventDefault();if(!canEdit())return;try{const p=formPayload(),id=$('editId').value;setBusy(true,id?'Salvataggio modifica...':'Salvataggio viaggio...');let q=id?sb.from('registro_viaggi').update(p).eq('id',id):sb.from('registro_viaggi').insert(p);const {data,error}=await q.select('id,numero').single();if(error)throw error;await loadData();resetForm();showView('archivio');alert('Viaggio '+(id?'aggiornato':'salvato')+' correttamente · N° '+data.numero)}catch(e){showError(e,'Salvataggio')}finally{setBusy(false)}});
function activeTrips(){return trips.filter(x=>!x.eliminato_at)}
function filteredArchive(){let a=activeTrips();const ym=$('meseArchivio').value,q=$('fSearch').value.toLowerCase().trim(),dal=$('fDal').value,al=$('fAl').value,m=$('fMezzo').value;return a.filter(x=>(!ym||x.data.startsWith(ym))&&(!dal||x.data>=dal)&&(!al||x.data<=al)&&(!m||x.mezzo===m)&&(!q||[x.numero,x.tipo_servizio,x.richiedente_servizio,x.scheda_118,x.nome_paziente,x.cognome_paziente,x.luogo_partenza,x.luogo_carico,x.luogo_fine,personName(x.autista_badge),personName(x.capo_badge),personName(x.soccorritore_1_badge),personName(x.soccorritore_2_badge)].join(' ').toLowerCase().includes(q)))}
function monthRecord(ym){return months.find(m=>(m.mese||'').slice(0,7)===ym)}
function isMonthClosed(ym){const m=monthRecord(ym);if(m)return !!m.chiuso;return !!ym&&ym<ymNow()}
function monthStatusText(ym){return isMonthClosed(ym)?'🔒 MESE CHIUSO':'🟢 MESE APERTO'}
function renderArchivio(){const ym=$('meseArchivio').value;$('statoMeseArchivio').textContent=monthStatusText(ym);const a=filteredArchive();$('archiveBody').innerHTML=a.length?a.map(x=>{const closed=isMonthClosed(x.data.slice(0,7));const actions=!canEdit()?'Solo lettura':closed?'<span style="font-weight:800;color:#8a5a00">🔒 Chiuso</span>':'<button class="mini" style="background:#2879e8" onclick="editTrip(\''+x.id+'\')">Modifica</button>'+(isAdmin()?' <button class="mini" style="background:#d84d4d" onclick="deleteTrip(\''+x.id+'\')">Elimina</button>':'');return '<tr><td><b>'+x.numero+'</b></td><td>'+esc(x.tipo_servizio)+'</td><td>'+esc(x.richiedente_servizio)+'</td><td>'+esc(x.scheda_118||'')+'</td><td>'+esc(x.nome_paziente||'')+'</td><td>'+esc(x.cognome_paziente||'')+'</td><td>'+esc(vehicleName(x.mezzo))+'</td><td>'+esc(x.targa)+'</td><td>'+x.km_iniziali+'</td><td>'+x.km_finali+'</td><td>'+x.km_percorsi+'</td><td>'+esc(x.data)+'</td><td>'+esc(x.ora_partenza||'')+'</td><td>'+esc(x.luogo_partenza||'')+'</td><td>'+esc(x.ora_destinazione||'')+'</td><td>'+esc(x.luogo_carico||'')+'</td><td>'+esc(x.tipo_luogo_carico||'')+'</td><td>'+esc(x.altro_luogo_carico||'')+'</td><td>'+esc(x.luogo_fine||'')+'</td><td>'+esc(x.ora_fine||'')+'</td><td>'+esc(personName(x.autista_badge))+'</td><td>'+esc(personName(x.capo_badge))+'</td><td>'+esc(personName(x.soccorritore_1_badge))+'</td><td>'+esc(personName(x.soccorritore_2_badge))+'</td><td>'+esc(x.metodo_pagamento||'')+'</td><td>'+esc(x.numero_ricevuta||'')+'</td><td>'+money(x.importo)+'</td><td>'+esc(x.ospedale_clinica||'')+'</td><td>'+actions+'</td></tr>'}).join(''):'<tr><td colspan="29" class="empty">Nessun viaggio trovato</td></tr>'}
async function editTrip(id){if(!canEdit())return;const x=trips.find(t=>t.id===id);if(!x)return;if(isMonthClosed(x.data.slice(0,7)))return alert('Il mese di questo viaggio è chiuso.');$('editId').value=x.id;$('numero').value=x.numero;$('data').value=x.data;$('tipoServizio').value=x.tipo_servizio;$('richiedenteServizio').value=x.richiedente_servizio;$('scheda118').value=x.scheda_118||'';$('nomePaziente').value=x.nome_paziente||'';$('cognomePaziente').value=x.cognome_paziente||'';$('mezzo').value=x.mezzo;$('targa').value=x.targa;$('kmIniziali').value=x.km_iniziali;$('kmFinali').value=x.km_finali;$('km').value=x.km_percorsi;$('oraPartenza').value=x.ora_partenza||'';$('partenza').value=x.luogo_partenza||'';$('oraDest').value=x.ora_destinazione||'';$('luogoCarico').value=x.luogo_carico||'';$('tipoLuogoCarico').value=x.tipo_luogo_carico||'';$('altroLuogoCarico').value=x.altro_luogo_carico||'';$('destinazione').value=x.luogo_fine||'';$('ospedale').value=x.ospedale_clinica||'';$('oraFine').value=x.ora_fine||'';$('metodoPagamento').value=x.metodo_pagamento||'';$('numeroRicevuta').value=x.numero_ricevuta||'';$('importo').value=x.importo||0;$('autista').value=x.autista_badge||'';$('capo').value=x.capo_badge||'';$('soc1').value=x.soccorritore_1_badge||'';$('soc2').value=x.soccorritore_2_badge||'';$('note').value=x.note||'';$('altroLuogoWrap').style.display=x.tipo_luogo_carico==='Altro'?'flex':'none';syncPaziente118();$('formTitle').textContent='Modifica viaggio N° '+x.numero;showView('nuovo')}
async function deleteTrip(id){if(!isAdmin())return;const x=trips.find(t=>t.id===id);if(!x)return;if(!confirm('Spostare il viaggio N° '+x.numero+' nel cestino?'))return;const {error}=await sb.from('registro_viaggi').update({eliminato_at:new Date().toISOString(),eliminato_da:currentUser.id}).eq('id',id);if(error)return showError(error,'Eliminazione');await loadData()}
function clearFilters(){$('fSearch').value='';$('fDal').value='';$('fAl').value='';$('fMezzo').value='';renderArchivio()}
function buildStats(a){const km=a.reduce((s,x)=>s+(+x.km_percorsi||0),0),imp=a.reduce((s,x)=>s+(+x.importo||0),0);const count=f=>{const o={};a.forEach(x=>{const k=(f(x)||'Non specificato');o[k]=(o[k]||0)+1});return o};const pag={};a.forEach(x=>{const k=x.metodo_pagamento||'Non specificato';pag[k]??={viaggi:0,importo:0};pag[k].viaggi++;pag[k].importo+=(+x.importo||0)});return {viaggi:a.length,km,importi:imp,mediaKm:a.length?km/a.length:0,schede118:a.filter(x=>x.scheda_118).length,privati:a.filter(x=>x.richiedente_servizio==='PRIVATO').length,importoMedio:a.length?imp/a.length:0,viaggiConIncasso:a.filter(x=>+x.importo>0).length,perMezzo:count(x=>x.mezzo),perTipo:count(x=>x.tipo_servizio),perRichiedente:count(x=>x.richiedente_servizio),pagamenti:pag,destinazioni:count(x=>x.luogo_fine)}}
function statsTable(obj){const r=Object.entries(obj||{}).sort((a,b)=>b[1]-a[1]);return r.length?'<table style="min-width:0"><tbody>'+r.map(x=>'<tr><td>'+esc(x[0])+'</td><td><b>'+x[1]+'</b></td></tr>').join('')+'</tbody></table>':'<div class="empty">Nessun dato</div>'}
function paymentTable(obj){const r=Object.entries(obj||{}).sort((a,b)=>b[1].importo-a[1].importo);return r.length?'<table style="min-width:0"><thead><tr><th>Metodo</th><th>Viaggi</th><th>Importo</th></tr></thead><tbody>'+r.map(x=>'<tr><td>'+esc(x[0])+'</td><td>'+x[1].viaggi+'</td><td>'+money(x[1].importo)+'</td></tr>').join('')+'</tbody></table>':'<div class="empty">Nessun dato</div>'}
function renderBars(target,a){const c=vehicles.map(v=>({name:vehicleName(v.codice),n:a.filter(x=>x.mezzo===v.codice).length})),mx=Math.max(1,...c.map(x=>x.n));$(target).innerHTML=c.map(x=>'<div class="barrow"><b>'+esc(x.name)+'</b><div class="bar"><i style="width:'+(x.n/mx*100)+'%"></i></div><span>'+x.n+' viaggi</span></div>').join('')}
function renderStats(){const ym=$('meseStatistiche').value,closed=isMonthClosed(ym),mr=monthRecord(ym);$('statoMeseStatistiche').textContent=monthStatusText(ym);let a=activeTrips().filter(x=>x.data.startsWith(ym)),s=(closed&&mr?.statistiche&&Object.keys(mr.statistiche).length)?mr.statistiche:buildStats(a);$('snapshotInfo').textContent=closed&&mr?.statistiche?'Statistiche consolidate alla chiusura del mese':'Statistiche aggiornate in tempo reale';$('sViaggi').textContent=s.viaggi||0;$('sKm').textContent=Math.round(s.km||0).toLocaleString('it-IT');$('sImporti').textContent=money(s.importi);$('sMedia').textContent=Math.round(s.mediaKm||0);$('s118').textContent=s.schede118||0;$('sPrivati').textContent=s.privati||0;$('sImportoMedio').textContent=money(s.importoMedio);$('sPagati').textContent=s.viaggiConIncasso||0;renderBars('barsStats',a);$('tipoStats').innerHTML=statsTable(s.perTipo);$('richiedenteStats').innerHTML=statsTable(s.perRichiedente);$('pagamentiStats').innerHTML=paymentTable(s.pagamenti);const dest=Object.entries(s.destinazioni||{}).sort((a,b)=>b[1]-a[1]).slice(0,10);$('destStats').innerHTML=dest.length?'<table style="min-width:0"><tbody>'+dest.map(x=>'<tr><td>'+esc(x[0])+'</td><td><b>'+x[1]+'</b></td></tr>').join('')+'</tbody></table>':'<div class="empty">Nessun dato</div>';$('riepilogoStats').innerHTML='<table style="min-width:0"><tbody><tr><th>Mese</th><td>'+esc(ym)+'</td></tr><tr><th>Stato</th><td>'+(closed?'Chiuso':'Aperto')+'</td></tr><tr><th>Viaggi</th><td>'+s.viaggi+'</td></tr><tr><th>Km</th><td>'+Math.round(s.km||0).toLocaleString('it-IT')+'</td></tr><tr><th>Importi</th><td>'+money(s.importi)+'</td></tr><tr><th>Schede 118</th><td>'+s.schede118+'</td></tr></tbody></table>';updateMonthAdminButton(ym,closed)}
function updateMonthAdminButton(ym,closed){const b=$('monthAdminBtn');if(!b)return;if(!isAdmin()||!ym||ym>=ymNow()){b.style.display='none';return}b.style.display='inline-block';b.textContent=closed?'Riapri mese':'Chiudi mese';b.className='btn '+(closed?'warning':'danger')}
async function toggleMonth(){if(!isAdmin())return;const ym=$('meseStatistiche').value,closed=isMonthClosed(ym);if(!ym||ym>=ymNow())return;if(!confirm((closed?'Riaprire':'Chiudere')+' il mese '+ym+'?'))return;const mese=ym+'-01';let payload={mese,chiuso:!closed,updated_at:new Date().toISOString()};if(!closed){const s=buildStats(activeTrips().filter(x=>x.data.startsWith(ym)));payload.statistiche={...s,mese,generatoIl:new Date().toISOString()};payload.chiuso_at=new Date().toISOString();payload.chiuso_da=currentUser.id}else{payload.statistiche={};payload.chiuso_at=null;payload.chiuso_da=null}const {error}=await sb.from('registro_viaggi_mesi').upsert(payload,{onConflict:'mese'});if(error)return showError(error,'Gestione mese');await loadData()}
function renderDashboard(){const ym=ymNow(),a=activeTrips().filter(x=>x.data.startsWith(ym)),s=buildStats(a);$('kViaggi').textContent=s.viaggi;$('kKm').textContent=s.km.toLocaleString('it-IT');$('kImporti').textContent=money(s.importi);const counts=Object.entries(s.perMezzo).sort((a,b)=>b[1]-a[1]);$('kMezzo').textContent=counts[0]?vehicleName(counts[0][0]).replace('Ambulanza ',''):'–';const u=activeTrips().slice().sort((a,b)=>b.data.localeCompare(a.data)||b.numero-a.numero).slice(0,5);$('ultimi').innerHTML=u.length?'<div class="tablewrap"><table style="min-width:0"><thead><tr><th>N°</th><th>Data</th><th>Mezzo</th><th>Destinazione</th><th>Km</th></tr></thead><tbody>'+u.map(x=>'<tr><td>'+x.numero+'</td><td>'+esc(x.data)+'</td><td>'+esc(vehicleName(x.mezzo))+'</td><td>'+esc(x.luogo_fine||'')+'</td><td>'+x.km_percorsi+'</td></tr>').join('')+'</tbody></table></div>':'<div class="empty">Nessun viaggio</div>';renderBars('barsDashboard',a)}
function renderAll(){if(!currentAccess)return;renderDashboard();renderArchivio();renderStats();renderVehicles()}
function renderVehicles(){$('vehicleGrid').innerHTML=vehicles.map(v=>'<div class="vehicle"><strong>'+esc(vehicleName(v.codice))+'</strong><span>Targa: <b>'+esc(v.targa)+'</b></span><span>Stato: attivo</span></div>').join('')}
function exportXLSX(){const a=filteredArchive();if(!a.length)return alert('Nessun viaggio da esportare.');const rows=a.map(x=>({'N°':x.numero,'Data':x.data,'Tipo servizio':x.tipo_servizio,'Richiedente':x.richiedente_servizio,'Scheda 118':x.scheda_118||'','Nome paziente':x.nome_paziente||'','Cognome paziente':x.cognome_paziente||'','Mezzo':vehicleName(x.mezzo),'Targa':x.targa,'Km iniziali':x.km_iniziali,'Km finali':x.km_finali,'Km percorsi':x.km_percorsi,'Ora partenza':x.ora_partenza||'','Luogo partenza':x.luogo_partenza||'','Ora destinazione':x.ora_destinazione||'','Luogo carico':x.luogo_carico||'','Tipo luogo carico':x.tipo_luogo_carico||'','Luogo fine':x.luogo_fine||'','Ospedale/Clinica':x.ospedale_clinica||'','Ora fine':x.ora_fine||'','Autista':personName(x.autista_badge),'Capo equipaggio':personName(x.capo_badge),'Soccorritore 1':personName(x.soccorritore_1_badge),'Soccorritore 2':personName(x.soccorritore_2_badge),'Metodo pagamento':x.metodo_pagamento||'','N° ricevuta':x.numero_ricevuta||'','Importo €':Number(x.importo||0),'Note':x.note||''}));const ws=XLSX.utils.json_to_sheet(rows),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Registro Viaggi');XLSX.writeFile(wb,'Registro_Viaggi_'+($('meseArchivio').value||'completo')+'.xlsx')}
function printMonth(){const a=filteredArchive(),ym=$('meseArchivio').value;if(!a.length)return alert('Nessun viaggio da stampare.');const w=window.open('','_blank');w.document.write('<!doctype html><html><head><meta charset="utf-8"><title>Registro Viaggi '+esc(ym)+'</title><style>body{font-family:Arial;padding:20px;font-size:11px}h1{margin:0}table{width:100%;border-collapse:collapse;margin-top:15px}th,td{border:1px solid #888;padding:5px;text-align:left}th{background:#eee}@page{size:A4 landscape;margin:8mm}</style></head><body><h1>Croce Gialla Emergenza ODV</h1><h2>Registro Viaggi · '+esc(ym)+'</h2><p>'+monthStatusText(ym)+' · Viaggi: '+a.length+' · Km: '+a.reduce((s,x)=>s+x.km_percorsi,0)+' · Importi: '+money(a.reduce((s,x)=>s+Number(x.importo||0),0))+'</p><table><thead><tr><th>N°</th><th>Data</th><th>Servizio</th><th>Mezzo</th><th>Partenza</th><th>Carico</th><th>Fine</th><th>Km</th><th>Autista</th><th>Capo</th><th>Soccorritori</th><th>Importo</th></tr></thead><tbody>'+a.map(x=>'<tr><td>'+x.numero+'</td><td>'+esc(x.data)+'</td><td>'+esc(x.tipo_servizio)+'</td><td>'+esc(vehicleName(x.mezzo))+'</td><td>'+esc(x.luogo_partenza||'')+'</td><td>'+esc(x.luogo_carico||'')+'</td><td>'+esc(x.luogo_fine||'')+'</td><td>'+x.km_percorsi+'</td><td>'+esc(personName(x.autista_badge))+'</td><td>'+esc(personName(x.capo_badge))+'</td><td>'+esc([personName(x.soccorritore_1_badge),personName(x.soccorritore_2_badge)].filter(Boolean).join(', '))+'</td><td>'+money(x.importo)+'</td></tr>').join('')+'</tbody></table><script>window.onload=()=>window.print()<\/script></body></html>');w.document.close()}
async function loadAdminTools(){if(!isAdmin())return;const [b,d,a]=await Promise.all([sb.from('registro_viaggi_backup').select('id,creato_il,tipo').order('creato_il',{ascending:false}).limit(10),sb.from('registro_viaggi').select('id,numero,data,tipo_servizio,eliminato_at').not('eliminato_at','is',null).order('eliminato_at',{ascending:false}).limit(30),sb.from('registro_viaggi_audit').select('id,viaggio_id,azione,actor_user_id,avvenuto_il').order('avvenuto_il',{ascending:false}).limit(20)]);if(b.error||d.error||a.error)return showError(b.error||d.error||a.error,'Strumenti amministrazione');$('backupList').innerHTML=(b.data||[]).length?(b.data||[]).map(x=>'<div class="box" style="margin:6px 0"><b>'+esc(x.tipo)+'</b> · '+new Date(x.creato_il).toLocaleString('it-IT')+'</div>').join(''):'<div class="empty">Nessun backup automatico ancora disponibile.</div>';$('trashList').innerHTML=(d.data||[]).length?(d.data||[]).map(x=>'<div class="box" style="margin:6px 0">N° <b>'+x.numero+'</b> · '+esc(x.data)+' · '+esc(x.tipo_servizio)+' <button class="mini" style="background:#2c9a62;float:right" onclick="restoreTrip(\''+x.id+'\')">Ripristina</button></div>').join(''):'<div class="empty">Cestino vuoto.</div>';$('auditList').innerHTML=(a.data||[]).length?(a.data||[]).map(x=>'<div class="box" style="margin:6px 0"><b>'+esc(x.azione)+'</b> · '+new Date(x.avvenuto_il).toLocaleString('it-IT')+' · viaggio '+esc(x.viaggio_id||'')+'</div>').join(''):'<div class="empty">Nessuna attività.</div>'}
async function restoreTrip(id){if(!isAdmin())return;if(!confirm('Ripristinare questo viaggio?'))return;const {error}=await sb.from('registro_viaggi').update({eliminato_at:null,eliminato_da:null}).eq('id',id);if(error)return showError(error,'Ripristino');await loadData();await loadAdminTools()}
async function downloadBackup(){if(!isAdmin())return;const [t,m]=await Promise.all([sb.from('registro_viaggi').select('*').order('numero'),sb.from('registro_viaggi_mesi').select('*').order('mese')]);if(t.error||m.error)return showError(t.error||m.error,'Backup');const blob=new Blob([JSON.stringify({creatoIl:new Date().toISOString(),viaggi:t.data,mesi:m.data},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='backup_registro_viaggi_'+iso(new Date())+'.json';a.click();URL.revokeObjectURL(url)}
document.addEventListener('DOMContentLoaded',()=>{$('loginForm').addEventListener('submit',login);$('logoutBtn').addEventListener('click',logout);const ym=ymNow();$('meseArchivio').value=ym;$('meseStatistiche').value=ym;$('meseArchivio').addEventListener('change',renderArchivio);$('meseStatistiche').addEventListener('change',renderStats);bootstrap()});
