const SUPABASE_URL='https://ihottewckpwpwqzpxusl.supabase.co';
const SUPABASE_KEY='sb_publishable_K7aTp6hLR_Pcpn7UGvArLg_DEgBjlH4';
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);

let currentUser=null,currentAccess=null;
let trips=[],personale=[],vehicles=[],months=[];
const comuni=['Sede','Agrate Conturbia','Arona','Baveno','Biandrate','Boca','Bogogno','Bolzano Novarese','Borgo Ticino','Borgomanero','Briga Novarese','Cameri','Carpignano Sesia','Casalbeltrame','Casaleggio Novara','Casalino','Casalvolone','Castelletto Sopra Ticino','Cavaglio d’Agogna','Cavallirio','Cerano','Colazza','Comignago','Cressa','Cureggio','Divignano','Dormelletto','Fara Novarese','Fontaneto d’Agogna','Galliate','Garbagna Novarese','Gargallo','Gattico-Veruno','Ghemme','Gozzano','Granozzo con Monticello','Invorio','Landiona','Lesa','Maggiora','Mandello Vitta','Marano Ticino','Massino Visconti','Meina','Mezzomerico','Miasino','Momo','Nebbiuno','Nibbiola','Novara','Oleggio','Oleggio Castello','Orta San Giulio','Paruzzaro','Pella','Pettenasco','Pisano','Pogno','Pombia','Prato Sesia','Recetto','Romagnano Sesia','Romentino','San Maurizio d’Opaglio','San Nazzaro Sesia','San Pietro Mosezzo','Sillavengo','Sizzano','Soriso','Sozzago','Suno','Terdobbiate','Trecate','Vaprio d’Agogna','Varallo Pombia','Vespolate','Vicolungo','Vinzaglio','Borgosesia','Gattinara','Santhià','Vercelli','Cannobio','Domodossola','Gravellona Toce','Omegna','Stresa','Verbania'];
const serviceTypes=['Emergenza / Urgenza','Dimissione','Trasferimento','Visita','Trasporto semplice','Assistenza manifestazione','Servizio sociale','Altro'];
const richiedenti=['C.O NOVARA','PRIVATO','RSA','COMUNE',"SOCIETA' SPORTIVA"];
const tipiLuogoCarico=['Casa','Ospedale','RSA','Scuola','Impianto sportivo','Altro'];
const metodiPagamento=['Bonifico','Bonifico istantaneo','Contante','POS'];
const ospedali=['','Ospedale SS. Trinità - Borgomanero','Ospedale Maggiore della Carità - Novara','Ospedale Santissima Trinità - Arona','Ospedale Castelli - Verbania','Ospedale San Biagio - Domodossola','Ospedale degli Infermi - Biella','Ospedale Sant’Andrea - Vercelli','Ospedale Cardinal Massaia - Asti','Ospedale Santa Croce e Carle - Cuneo','Ospedale Mauriziano - Torino','Ospedale Molinette - Torino','Ospedale San Luigi Gonzaga - Orbassano','Ospedale Maggiore Policlinico - Milano','Ospedale Niguarda - Milano','Ospedale San Raffaele - Milano','Humanitas - Rozzano','Ospedale di Circolo - Varese','Ospedale Sant’Anna - Como','Ospedale Papa Giovanni XXIII - Bergamo','Spedali Civili - Brescia','Policlinico San Matteo - Pavia','Ospedale Santa Chiara - Trento','AOU Verona','AOU Padova','Ospedale Maggiore - Bologna','AOU Careggi - Firenze','AOU Pisana - Pisa','Ospedale di Livorno','Ospedale Misericordia - Grosseto'];

const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const iso=d=>{const x=new Date(d);const off=x.getTimezoneOffset();return new Date(x.getTime()-off*60000).toISOString().slice(0,10)};
const ymNow=()=>iso(new Date()).slice(0,7);
const money=n=>'€ '+Number(n||0).toLocaleString('it-IT',{minimumFractionDigits:2,maximumFractionDigits:2});
const role=()=>currentAccess?.ruolo||'';
const canEdit=()=>['AMMINISTRATORE','CENTRALINO'].includes(role());
const isAdmin=()=>role()==='AMMINISTRATORE';
const personName=badge=>personale.find(p=>p.badge===badge)?.nome_completo||badge||'';
const vehicleName=code=>{const v=vehicles.find(x=>x.codice===code);if(!v)return code||'';return v.tipologia==='AMBULANZA'?'Ambulanza '+v.codice:'Trasporto semplice '+v.codice};

function showError(e,prefix='Errore'){console.error(e);alert(prefix+': '+(e?.message||e||'operazione non riuscita'))}
function setBusy(on,msg='Caricamento...'){const el=$('busyOverlay');if(!el)return;el.style.display=on?'flex':'none';$('busyText').textContent=msg}
async function login(e){e?.preventDefault();const email=$('loginEmail').value.trim(),password=$('loginPassword').value;$('loginError').textContent='';const {error}=await sb.auth.signInWithPassword({email,password});if(error){$('loginError').textContent='Accesso non riuscito. Controlla email e password.';return}await bootstrap()}
async function logout(){await sb.auth.signOut();location.reload()}
async function bootstrap(){
  setBusy(true,'Verifica accesso...');
  const {data:{user},error}=await sb.auth.getUser();
  if(error||!user){setBusy(false);$('loginOverlay').style.display='flex';return}
  currentUser=user;
  const {data:acc,error:ae}=await sb.from('accessi_app').select('user_id,nome,ruolo,attivo').eq('user_id',user.id).eq('attivo',true).maybeSingle();
  if(ae||!acc||!['AMMINISTRATORE','CENTRALINO','CONSULTAZIONE'].includes(acc.ruolo)){await sb.auth.signOut();setBusy(false);$('loginOverlay').style.display='flex';$('loginError').textContent='Utente non abilitato al Registro Viaggi.';return}
  currentAccess=acc;$('loginOverlay').style.display='none';$('who').textContent=(acc.nome||user.email)+' · '+acc.ruolo;applyRoleUi();
  try{await loadResources();await loadData();initStaticSelects();resetForm();showView(role()==='CONSULTAZIONE'?'archivio':'nuovo')}catch(e){showError(e,'Caricamento iniziale')}setBusy(false)
}
function applyRoleUi(){const edit=canEdit(),admin=isAdmin();document.querySelector('[data-view="nuovo"]').style.display=edit?'block':'none';document.querySelector('[data-view="impostazioni"]').style.display=admin?'block':'none';$('tripForm').querySelectorAll('input,select,textarea,button').forEach(x=>x.disabled=!edit);$('logoutBtn').style.display='inline-block'}
async function loadResources(){
  const [p,v]=await Promise.all([
    sb.from('personale').select('badge,nome_completo,autista,capo_servizio,soccorritore,secondo_soccorritore,dipendente,attivo,stato_anagrafico').eq('attivo',true).eq('stato_anagrafico','ATTIVO').order('badge'),
    sb.from('mezzi').select('codice,tipologia,targa,attivo').eq('attivo',true).order('codice')
  ]);if(p.error)throw p.error;if(v.error)throw v.error;personale=p.data||[];vehicles=v.data||[]
}
async function loadData(){
  const [t,m]=await Promise.all([sb.from('registro_viaggi').select('*').order('data',{ascending:false}).order('numero',{ascending:false}),sb.from('registro_viaggi_mesi').select('*').order('mese',{ascending:false})]);
  if(t.error)throw t.error;if(m.error)throw m.error;trips=t.data||[];months=m.data||[];renderAll()
}
function initStaticSelects(){
  $('tipoServizio').innerHTML='<option value="">Seleziona tipo servizio</option>'+serviceTypes.map(v=>'<option>'+esc(v)+'</option>').join('');
  $('richiedenteServizio').innerHTML='<option value="">Seleziona richiedente</option>'+richiedenti.map(v=>'<option>'+esc(v)+'</option>').join('');
  $('tipoLuogoCarico').innerHTML='<option value="">Seleziona tipo luogo</option>'+tipiLuogoCarico.map(v=>'<option>'+esc(v)+'</option>').join('');
  $('metodoPagamento').innerHTML='<option value="">Seleziona metodo</option>'+metodiPagamento.map(v=>'<option>'+esc(v)+'</option>').join('');
  $('ospedale').innerHTML=ospedali.map(v=>'<option value="'+esc(v)+'">'+esc(v||'Nessun ospedale/clinica')+'</option>').join('');
  const vo=vehicles.map(v=>'<option value="'+esc(v.codice)+'">'+esc(vehicleName(v.codice))+'</option>').join('');$('mezzo').innerHTML='<option value="">Seleziona mezzo</option>'+vo;$('fMezzo').innerHTML='<option value="">Tutti i mezzi</option>'+vo;
  fillRoles();renderComboList('partenza','');renderComboList('luogoCarico','');renderComboList('destinazione','');renderEquipaggi()
}
function fillRoles(){const fill=(id,filter,label)=>{$(id).innerHTML='<option value="">Seleziona '+label+'</option>'+personale.filter(filter).map(p=>'<option value="'+esc(p.badge)+'">'+esc(p.badge+' · '+p.nome_completo)+'</option>').join('')};fill('autista',p=>p.autista,'autista');fill('capo',p=>p.capo_servizio,'capo equipaggio');fill('soc1',p=>p.soccorritore,'soccorritore');fill('soc2',p=>p.secondo_soccorritore||p.soccorritore,'secondo soccorritore')}
function renderEquipaggi(){const rows=personale.map(p=>'<tr><td><b>'+esc(p.badge)+'</b></td><td>'+esc(p.nome_completo)+'</td><td>'+(p.autista?'✓':'')+'</td><td>'+(p.capo_servizio?'✓':'')+'</td><td>'+(p.soccorritore?'✓':'')+'</td><td>'+(p.secondo_soccorritore?'✓':'')+'</td></tr>').join('');$('equipaggi').querySelector('.panel').innerHTML='<h2>Volontari e qualifiche sincronizzati</h2><div class="notice">Elenco letto direttamente dal database del personale. Le tendine del viaggio si aggiornano in base alle qualifiche attive.</div><div class="tablewrap"><table style="min-width:700px"><thead><tr><th>Badge</th><th>Volontario</th><th>Autista</th><th>Capo equipaggio</th><th>Soccorritore</th><th>Secondo soccorritore</th></tr></thead><tbody>'+rows+'</tbody></table></div>'}
function renderComboList(id,filter){const list=$(id+'List');if(!list)return;const q=(filter||'').toLowerCase();const vals=comuni.filter(v=>!q||v.toLowerCase().includes(q));list.innerHTML=vals.map(v=>'<div onclick="selectCombo(\''+id+'\',\''+v.replace(/'/g,"\\'")+'\')">'+esc(v)+'</div>').join('')}
function toggleCombo(id){document.querySelectorAll('.combo-list').forEach(x=>{if(x.id!==id+'List')x.classList.remove('open')});renderComboList(id,$(id).value);$(id+'List').classList.toggle('open')}
function selectCombo(id,value){$(id).value=value;$(id+'List').classList.remove('open')}
['partenza','luogoCarico','destinazione'].forEach(id=>document.addEventListener('input',e=>{if(e.target.id===id){renderComboList(id,e.target.value);$(id+'List').classList.add('open')}}));document.addEventListener('click',e=>{if(!e.target.closest('.combo'))document.querySelectorAll('.combo-list').forEach(x=>x.classList.remove('open'))});
function showView(id){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');document.querySelectorAll('.navbtn').forEach(b=>b.classList.toggle('active',b.dataset.view===id));if(id==='nuovo'&&!$('editId').value)resetForm();if(id==='impostazioni'&&isAdmin())loadAdminTools();window.scrollTo(0,0)}
document.querySelectorAll('.navbtn').forEach(b=>b.onclick=()=>showView(b.dataset.view));
function latestTripForVehicle(code,excludeId=''){return activeTrips().filter(x=>x.mezzo===code&&x.id!==excludeId).sort((a,b)=>b.data.localeCompare(a.data)||Number(b.numero)-Number(a.numero))[0]||null}
function syncVehicle(){const v=vehicles.find(x=>x.codice===$('mezzo').value);$('targa').value=v?.targa||'';const id=$('editId').value,last=latestTripForVehicle($('mezzo').value,id);if(last&&!id){$('kmIniziali').value=last.km_finali;$('kmContinuityHint').textContent='Ultimo km registrato per '+vehicleName(v.codice)+': '+Number(last.km_finali).toLocaleString('it-IT')+' km';$('kmContinuityHint').style.color='#2c9a62';calcKm()}else if(last){$('kmContinuityHint').textContent='Ultimo altro viaggio del mezzo: '+Number(last.km_finali).toLocaleString('it-IT')+' km';$('kmContinuityHint').style.color='#68758a'}else{$('kmContinuityHint').textContent='Nessun km precedente registrato per questo mezzo';$('kmContinuityHint').style.color='#68758a'}}
function calcKm(){const i=Number($('kmIniziali').value),f=Number($('kmFinali').value);$('km').value=(Number.isFinite(i)&&Number.isFinite(f)&&f>=i)?f-i:''}
function syncPaziente118(){const has=($('scheda118').value||'').trim()!=='';['nomePaziente','cognomePaziente'].forEach(id=>{const el=$(id);if(has){el.value='';el.disabled=true;el.style.background='#eef1f5';el.placeholder='Disattivato: presente scheda 118'}else{el.disabled=false;el.style.background='white';el.placeholder=id==='nomePaziente'?'Nome':'Cognome'}})}
function syncImporto(){
  const is118=$('tipoServizio').value==='Emergenza / Urgenza';
  const el=$('importo');
  if(is118){
    el.value='';
    el.disabled=true;
    el.required=false;
    el.style.background='#eef1f5';
    el.placeholder='Non previsto per 118';
  }else{
    el.disabled=false;
    el.required=true;
    el.style.background='white';
    el.placeholder='Inserisci importo';
  }
}
$('mezzo').addEventListener('change',syncVehicle);$('kmIniziali').addEventListener('input',()=>{calcKm();const code=$('mezzo').value;if(!code)return;const last=latestTripForVehicle(code,$('editId').value);if(last&&Number($('kmIniziali').value)!==Number(last.km_finali)){$('kmContinuityHint').textContent='⚠ Attenzione: l’ultimo km finale registrato è '+Number(last.km_finali).toLocaleString('it-IT')+' km';$('kmContinuityHint').style.color='#b46b00'}else if(last){$('kmContinuityHint').textContent='✓ Continuità km corretta: '+Number(last.km_finali).toLocaleString('it-IT')+' km';$('kmContinuityHint').style.color='#2c9a62'}});$('kmFinali').addEventListener('input',calcKm);$('scheda118').addEventListener('input',syncPaziente118);
$('tipoLuogoCarico').addEventListener('change',()=>{const a=$('tipoLuogoCarico').value==='Altro';$('altroLuogoWrap').style.display=a?'flex':'none';if(!a)$('altroLuogoCarico').value=''});
$('tipoServizio').addEventListener('change',()=>{if($('tipoServizio').value==='Emergenza / Urgenza')$('scheda118').setAttribute('required','required');else $('scheda118').removeAttribute('required');syncImporto()});
function resetForm(){if(!canEdit())return;$('tripForm').reset();$('editId').value='';$('numero').value='Automatico';$('data').value=iso(new Date());$('formTitle').textContent='Nuovo viaggio';$('km').value='';$('targa').value='';$('kmContinuityHint').textContent='';$('altroLuogoWrap').style.display='none';syncPaziente118();syncImporto()}
function formPayload(){
  const badges=[$('autista').value,$('capo').value,$('soc1').value,$('soc2').value].filter(Boolean);if(new Set(badges).size!==badges.length)throw new Error('Lo stesso volontario non può essere inserito in più ruoli');
  const ki=Number($('kmIniziali').value),kf=Number($('kmFinali').value);if(!Number.isFinite(ki)||!Number.isFinite(kf)||kf<ki)throw new Error('I km finali devono essere uguali o superiori ai km iniziali');
  const is118=$('tipoServizio').value==='Emergenza / Urgenza';
  if(is118&&!$('scheda118').value.trim())throw new Error('Per Emergenza / Urgenza è obbligatorio il N° scheda 118');
  if(!is118){const imp=Number($('importo').value);if(!Number.isFinite(imp)||imp<=0)throw new Error('Per i servizi non 118 l’importo è obbligatorio e deve essere inserito manualmente');}
  const last=latestTripForVehicle($('mezzo').value,$('editId').value);if(last&&Number($('kmIniziali').value)!==Number(last.km_finali)){const ok=confirm('ATTENZIONE KM: l’ultimo viaggio di '+vehicleName($('mezzo').value)+' termina a '+Number(last.km_finali).toLocaleString('it-IT')+' km, mentre hai inserito '+Number($('kmIniziali').value).toLocaleString('it-IT')+' km iniziali. Vuoi salvare comunque?');if(!ok)throw new Error('Salvataggio annullato per controllo continuità km')}
  return {data:$('data').value,tipo_servizio:$('tipoServizio').value,richiedente_servizio:$('richiedenteServizio').value,numero_foglio_marcia:$('numeroFoglioMarcia').value.trim()||null,scheda_118:$('scheda118').value.trim()||null,nome_paziente:$('scheda118').value.trim()?null:($('nomePaziente').value.trim()||null),cognome_paziente:$('scheda118').value.trim()?null:($('cognomePaziente').value.trim()||null),mezzo:$('mezzo').value,targa:$('targa').value,km_iniziali:ki,km_finali:kf,ora_partenza:$('oraPartenza').value||null,luogo_partenza:$('partenza').value.trim()||null,ora_destinazione:$('oraDest').value||null,luogo_carico:$('luogoCarico').value.trim()||null,tipo_luogo_carico:$('tipoLuogoCarico').value||null,altro_luogo_carico:$('altroLuogoCarico').value.trim()||null,luogo_fine:$('destinazione').value.trim()||null,ospedale_clinica:$('ospedale').value||null,ora_fine:$('oraFine').value||null,metodo_pagamento:$('metodoPagamento').value||null,numero_ricevuta:$('numeroRicevuta').value.trim()||null,importo:is118?0:Number($('importo').value),autista_badge:$('autista').value||null,capo_badge:$('capo').value||null,soccorritore_1_badge:$('soc1').value||null,soccorritore_2_badge:$('soc2').value||null,note:$('note').value.trim()||null}
}
function tripWarnings(p){
  const w=[];
  if(!p.numero_foglio_marcia)w.push('manca il N° foglio marcia');
  if(!p.luogo_partenza)w.push('manca il luogo di partenza');
  if(!p.luogo_fine)w.push('manca il luogo fine');
  if(!p.ora_partenza||!p.ora_fine)w.push('manca l’orario di partenza o di fine');
  if(p.tipo_servizio!=='Emergenza / Urgenza'&&!(Number(p.importo)>0))w.push('manca l’importo del servizio');
  const crew=[p.autista_badge,p.capo_badge,p.soccorritore_1_badge,p.soccorritore_2_badge].filter(Boolean).length;
  const min=p.mezzo==='06'?1:(['07','08','09'].includes(p.mezzo)?2:1);
  if(crew<min)w.push('equipaggio incompleto: '+vehicleName(p.mezzo)+' richiede almeno '+min+' componente'+(min>1?'i':''));
  return w
}
function checkDuplicateFoglio(p,id=''){
  const key=(p.numero_foglio_marcia||'').trim().toLowerCase();
  if(!key)throw new Error('Il N° foglio marcia è obbligatorio');
  if(activeTrips().some(x=>x.id!==id&&(x.numero_foglio_marcia||'').trim().toLowerCase()===key))throw new Error('Esiste già un viaggio attivo con N° foglio marcia '+p.numero_foglio_marcia)
}
$('tripForm').addEventListener('submit',async e=>{e.preventDefault();if(!canEdit())return;try{const p=formPayload(),id=$('editId').value,x=id?trips.find(t=>t.id===id):null;if(x?.stato==='CHIUSO')throw new Error('Il foglio è chiuso. Deve essere riaperto da Amministrazione prima di modificarlo');checkDuplicateFoglio(p,id);const warnings=tripWarnings(p);if(warnings.length&&!confirm('ATTENZIONE: il viaggio può essere salvato aperto, ma non potrà essere chiuso finché non completi:\n\n• '+warnings.join('\n• ')+'\n\nVuoi salvarlo comunque come foglio APERTO?'))return;setBusy(true,id?'Salvataggio modifica...':'Salvataggio viaggio...');let q=id?sb.from('registro_viaggi').update(p).eq('id',id):sb.from('registro_viaggi').insert(p);const {data,error}=await q.select('id,numero').single();if(error)throw error;await loadData();const restWarn=employeeRestAnomalies(activeTrips()).filter(r=>r.successivo.id===data.id||r.precedente.id===data.id);resetForm();showView('archivio');alert('Viaggio '+(id?'aggiornato':'salvato')+' correttamente · N° '+data.numero+' · FOGLIO APERTO'+(restWarn.length?'\n\nATTENZIONE: possibile mancato riposo di 11 ore per '+[...new Set(restWarn.map(r=>r.nome))].join(', ')+'. Verifica nella pagina Controlli.':''))}catch(e){showError(e,'Salvataggio')}finally{setBusy(false)}});
function activeTrips(){return trips.filter(x=>!x.eliminato_at)}
function filteredArchive(){let a=activeTrips();const ym=$('meseArchivio').value,q=$('fSearch').value.toLowerCase().trim(),dal=$('fDal').value,al=$('fAl').value,m=$('fMezzo').value,st=$('fStato')?.value||'';return a.filter(x=>(!ym||x.data.startsWith(ym))&&(!dal||x.data>=dal)&&(!al||x.data<=al)&&(!m||x.mezzo===m)&&(!st||x.stato===st)&&(!q||[x.numero,x.numero_foglio_marcia,x.tipo_servizio,x.richiedente_servizio,x.scheda_118,x.nome_paziente,x.cognome_paziente,x.luogo_partenza,x.luogo_carico,x.luogo_fine,personName(x.autista_badge),personName(x.capo_badge),personName(x.soccorritore_1_badge),personName(x.soccorritore_2_badge)].join(' ').toLowerCase().includes(q)))}
function monthRecord(ym){return months.find(m=>(m.mese||'').slice(0,7)===ym)}
function isMonthClosed(ym){const m=monthRecord(ym);if(m)return !!m.chiuso;return !!ym&&ym<ymNow()}
function monthStatusText(ym){return isMonthClosed(ym)?'🔒 MESE CHIUSO':'🟢 MESE APERTO'}
function renderArchivio(){const ym=$('meseArchivio').value;$('statoMeseArchivio').textContent=monthStatusText(ym);const a=filteredArchive();$('archiveBody').innerHTML=a.length?a.map(x=>{const monthClosed=isMonthClosed(x.data.slice(0,7)),sheetClosed=x.stato==='CHIUSO';let actions;if(!canEdit())actions=sheetClosed?'🔒 Foglio chiuso':'Solo lettura';else if(monthClosed)actions='<span style="font-weight:800;color:#8a5a00">🔒 Mese chiuso</span>';else if(sheetClosed)actions='<span style="font-weight:800;color:#8a5a00">🔒 Foglio chiuso</span> <button class="mini" style="background:#53657d" onclick="printTrip(\''+x.id+'\')">Stampa foglio</button> <button class="mini" style="background:#d89428" onclick="reopenTrip(\''+x.id+'\')">Riapri</button>'+(isAdmin()?' <button class="mini" style="background:#d84d4d" onclick="deleteTrip(\''+x.id+'\')">Elimina</button>':'');else actions='<button class="mini" style="background:#53657d" onclick="printTrip(\''+x.id+'\')">Stampa foglio</button> <button class="mini" style="background:#2879e8" onclick="editTrip(\''+x.id+'\')">Modifica</button> <button class="mini" style="background:#2c9a62" onclick="closeTrip(\''+x.id+'\')">Chiudi foglio</button>'+(isAdmin()?' <button class="mini" style="background:#d84d4d" onclick="deleteTrip(\''+x.id+'\')">Elimina</button>':'');return '<tr><td><b>'+x.numero+'</b></td><td>'+(sheetClosed?'<span style="font-weight:800;color:#8a5a00">CHIUSO</span>':'<span style="font-weight:800;color:#2c9a62">APERTO</span>')+'</td><td>'+esc(x.numero_foglio_marcia||'')+'</td><td>'+esc(x.tipo_servizio)+'</td><td>'+esc(x.richiedente_servizio)+'</td><td>'+esc(x.scheda_118||'')+'</td><td>'+esc(x.nome_paziente||'')+'</td><td>'+esc(x.cognome_paziente||'')+'</td><td>'+esc(vehicleName(x.mezzo))+'</td><td>'+esc(x.targa)+'</td><td>'+x.km_iniziali+'</td><td>'+x.km_finali+'</td><td>'+x.km_percorsi+'</td><td>'+esc(x.data)+'</td><td>'+esc(x.ora_partenza||'')+'</td><td>'+esc(x.luogo_partenza||'')+'</td><td>'+esc(x.ora_destinazione||'')+'</td><td>'+esc(x.luogo_carico||'')+'</td><td>'+esc(x.tipo_luogo_carico||'')+'</td><td>'+esc(x.altro_luogo_carico||'')+'</td><td>'+esc(x.luogo_fine||'')+'</td><td>'+esc(x.ora_fine||'')+'</td><td>'+esc(personName(x.autista_badge))+'</td><td>'+esc(personName(x.capo_badge))+'</td><td>'+esc(personName(x.soccorritore_1_badge))+'</td><td>'+esc(personName(x.soccorritore_2_badge))+'</td><td>'+esc(x.metodo_pagamento||'')+'</td><td>'+esc(x.numero_ricevuta||'')+'</td><td>'+money(x.importo)+'</td><td>'+esc(x.ospedale_clinica||'')+'</td><td>'+actions+'</td></tr>'}).join(''):'<tr><td colspan="31" class="empty">Nessun viaggio trovato</td></tr>'}
async function editTrip(id){if(!canEdit())return;const x=trips.find(t=>t.id===id);if(!x)return;if(isMonthClosed(x.data.slice(0,7)))return alert('Il mese di questo viaggio è chiuso.');if(x.stato==='CHIUSO')return alert('Il foglio viaggio è chiuso. Amministrazione deve prima riaprirlo.');$('editId').value=x.id;$('numero').value=x.numero;$('data').value=x.data;$('tipoServizio').value=x.tipo_servizio;$('richiedenteServizio').value=x.richiedente_servizio;$('numeroFoglioMarcia').value=x.numero_foglio_marcia||'';$('scheda118').value=x.scheda_118||'';$('nomePaziente').value=x.nome_paziente||'';$('cognomePaziente').value=x.cognome_paziente||'';$('mezzo').value=x.mezzo;$('targa').value=x.targa;$('kmIniziali').value=x.km_iniziali;$('kmFinali').value=x.km_finali;$('km').value=x.km_percorsi;$('oraPartenza').value=x.ora_partenza||'';$('partenza').value=x.luogo_partenza||'';$('oraDest').value=x.ora_destinazione||'';$('luogoCarico').value=x.luogo_carico||'';$('tipoLuogoCarico').value=x.tipo_luogo_carico||'';$('altroLuogoCarico').value=x.altro_luogo_carico||'';$('destinazione').value=x.luogo_fine||'';$('ospedale').value=x.ospedale_clinica||'';$('oraFine').value=x.ora_fine||'';$('metodoPagamento').value=x.metodo_pagamento||'';$('numeroRicevuta').value=x.numero_ricevuta||'';$('importo').value=x.tipo_servizio==='Emergenza / Urgenza'?'':(x.importo||'');$('autista').value=x.autista_badge||'';$('capo').value=x.capo_badge||'';$('soc1').value=x.soccorritore_1_badge||'';$('soc2').value=x.soccorritore_2_badge||'';$('note').value=x.note||'';$('altroLuogoWrap').style.display=x.tipo_luogo_carico==='Altro'?'flex':'none';syncPaziente118();syncImporto();syncVehicle();$('formTitle').textContent='Modifica viaggio N° '+x.numero;showView('nuovo')}
async function closeTrip(id){if(!canEdit())return;const x=trips.find(t=>t.id===id);if(!x||x.stato==='CHIUSO')return;if(isMonthClosed(x.data.slice(0,7)))return alert('Il mese di questo viaggio è chiuso.');const w=tripWarnings(x);if(w.length)return alert('Impossibile chiudere il foglio. Completa prima:\n\n• '+w.join('\n• '));if(!confirm('Chiudere il foglio viaggio N° '+x.numero+'? Dopo la chiusura non sarà più modificabile finché Amministrazione non lo riapre.'))return;setBusy(true,'Chiusura foglio...');try{const {error}=await sb.from('registro_viaggi').update({stato:'CHIUSO'}).eq('id',id);if(error)throw error;await loadData();alert('Foglio viaggio N° '+x.numero+' chiuso correttamente.')}catch(e){showError(e,'Chiusura foglio')}finally{setBusy(false)}}
async function reopenTrip(id){if(!canEdit())return;const x=trips.find(t=>t.id===id);if(!x||x.stato!=='CHIUSO')return;if(isMonthClosed(x.data.slice(0,7)))return alert('Il mese è chiuso. Per riaprire il foglio occorre prima riaprire il mese.');if(!confirm('Riaprire il foglio viaggio N° '+x.numero+' per correggerlo? La riapertura resterà registrata nello storico modifiche.'))return;setBusy(true,'Riapertura foglio...');try{const {error}=await sb.from('registro_viaggi').update({stato:'APERTO'}).eq('id',id);if(error)throw error;await loadData();alert('Foglio viaggio N° '+x.numero+' riaperto.')}catch(e){showError(e,'Riapertura foglio')}finally{setBusy(false)}}
async function deleteTrip(id){if(!isAdmin())return;const x=trips.find(t=>t.id===id);if(!x)return;if(!confirm('Spostare il viaggio N° '+x.numero+' nel cestino?'+(x.stato==='CHIUSO'?'\n\nATTENZIONE: il foglio è CHIUSO e verrà eliminato comunque. L’operazione resterà registrata nello storico.':'')))return;let q=sb.from('registro_viaggi').update({eliminato_at:new Date().toISOString(),eliminato_da:currentUser.id});if(x.stato==='CHIUSO')q=q.eq('id',id).eq('stato','CHIUSO');else q=q.eq('id',id);const {error}=await q;if(error){if(x.stato==='CHIUSO'&&String(error.message||'').includes('riaperto'))return alert('Per eliminare un foglio chiuso serve aggiornare la regola del database. Sto mantenendo il foglio invariato per sicurezza.');return showError(error,'Eliminazione')}await loadData()}
function clearFilters(){$('fSearch').value='';$('fDal').value='';$('fAl').value='';$('fMezzo').value='';if($('fStato'))$('fStato').value='';renderArchivio()}
function tripDateTime(x,which){
  const t=which==='start'?x.ora_partenza:x.ora_fine;
  if(!x.data||!t)return null;
  const time=String(t).slice(0,8);
  const d=new Date(x.data+'T'+time);
  if(Number.isNaN(d.getTime()))return null;
  if(which==='end'&&x.ora_partenza&&x.ora_fine&&String(x.ora_fine).slice(0,8)<String(x.ora_partenza).slice(0,8))d.setDate(d.getDate()+1);
  return d
}
function crewBadges(x){return [x.autista_badge,x.capo_badge,x.soccorritore_1_badge,x.soccorritore_2_badge].filter(Boolean)}
function employeeRestAnomalies(source=activeTrips()){
  const employees=new Set(personale.filter(p=>p.dipendente).map(p=>p.badge));
  const by={};
  source.forEach(x=>crewBadges(x).filter(b=>employees.has(b)).forEach(b=>{(by[b]??=[]).push(x)}));
  const out=[];
  Object.entries(by).forEach(([badge,arr])=>{
    const rows=arr.map(x=>({x,start:tripDateTime(x,'start'),end:tripDateTime(x,'end')})).filter(z=>z.start&&z.end).sort((a,b)=>a.start-b.start);
    for(let i=1;i<rows.length;i++){
      const prev=rows[i-1],cur=rows[i],hours=(cur.start-prev.end)/3600000;
      if(hours<11)out.push({badge,nome:personName(badge),precedente:prev.x,successivo:cur.x,ore:hours})
    }
  });
  return out
}
function mileageAnomalies(source=activeTrips()){
  const out=[];
  vehicles.forEach(v=>{
    const arr=source.filter(x=>x.mezzo===v.codice).slice().sort((a,b)=>(a.data+(a.ora_partenza||'')).localeCompare(b.data+(b.ora_partenza||''))||Number(a.numero)-Number(b.numero));
    for(let i=1;i<arr.length;i++)if(Number(arr[i].km_iniziali)!==Number(arr[i-1].km_finali))out.push({mezzo:v.codice,prev:arr[i-1],cur:arr[i]})
  });
  return out
}
function duplicateSheetNumbers(source=activeTrips()){
  const map={};source.forEach(x=>{const k=(x.numero_foglio_marcia||'').trim().toLowerCase();if(k)(map[k]??=[]).push(x)});
  return Object.entries(map).filter(([,v])=>v.length>1)
}
function monthIssues(ym){
  const a=activeTrips().filter(x=>x.data.startsWith(ym));
  const aperti=a.filter(x=>x.stato!=='CHIUSO');
  const incompleti=a.filter(x=>tripWarnings(x).length);
  return {a,aperti,incompleti}
}
function renderControlli(){
  const ym=$('meseControlli')?.value||ymNow(),source=activeTrips().filter(x=>x.data.startsWith(ym));
  const km=mileageAnomalies(source),open=source.filter(x=>x.stato!=='CHIUSO'),crew=source.filter(x=>{const n=crewBadges(x).length,min=x.mezzo==='06'?1:(['07','08','09'].includes(x.mezzo)?2:1);return n<min}),times=source.filter(x=>!x.ora_partenza||!x.ora_fine),dups=duplicateSheetNumbers(source),incomplete=source.filter(x=>tripWarnings(x).length),rest=employeeRestAnomalies(activeTrips()).filter(r=>r.precedente.data.startsWith(ym)||r.successivo.data.startsWith(ym));
  const item=(title,rows,fmt)=>'<div class="panel"><h2>'+title+' <span style="font-size:12px;color:#68758a">('+rows.length+')</span></h2>'+(rows.length?rows.map(fmt).join(''):'<div class="empty">Nessuna anomalia rilevata</div>')+'</div>';
  $('controlliBody').innerHTML=
    item('Salti nei km',km,r=>'<div class="box" style="margin:6px 0"><b>'+esc(vehicleName(r.mezzo))+'</b> · viaggio N° '+r.prev.numero+' termina a '+r.prev.km_finali+' km, il successivo N° '+r.cur.numero+' parte da '+r.cur.km_iniziali+' km</div>')+
    item('Fogli ancora aperti',open,x=>'<div class="box" style="margin:6px 0">N° <b>'+x.numero+'</b> · '+esc(x.data)+' · '+esc(vehicleName(x.mezzo))+'</div>')+
    item('Equipaggi incompleti',crew,x=>'<div class="box" style="margin:6px 0">N° <b>'+x.numero+'</b> · '+esc(x.data)+' · '+esc(vehicleName(x.mezzo))+'</div>')+
    item('Fogli senza orari completi',times,x=>'<div class="box" style="margin:6px 0">N° <b>'+x.numero+'</b> · '+esc(x.data)+' · partenza '+esc(x.ora_partenza||'manca')+' · fine '+esc(x.ora_fine||'manca')+'</div>')+
    item('Doppio N° foglio marcia',dups,d=>'<div class="box" style="margin:6px 0"><b>'+esc(d[0])+'</b> · viaggi '+d[1].map(x=>x.numero).join(', ')+'</div>')+
    item('Servizi con dati incompleti',incomplete,x=>'<div class="box" style="margin:6px 0">N° <b>'+x.numero+'</b> · '+tripWarnings(x).map(esc).join(' · ')+'</div>')+
    item('Possibile mancato riposo di 11 ore - dipendenti',rest,r=>'<div class="box" style="margin:6px 0"><b>'+esc(r.nome)+'</b> · N° '+r.precedente.numero+' → N° '+r.successivo.numero+' · intervallo '+(Math.round(r.ore*10)/10)+' ore</div>');
  $('controlliSummary').textContent='Mese '+ym+' · '+source.length+' viaggi · '+open.length+' aperti · '+incomplete.length+' incompleti · '+rest.length+' possibili anomalie riposo'
}
function printTrip(id){
  const x=trips.find(t=>t.id===id);if(!x)return;
  const row=(a,b)=>'<tr><th>'+a+'</th><td>'+esc(b??'')+'</td></tr>';
  const w=window.open('','_blank');
  w.document.write('<!doctype html><html><head><meta charset="utf-8"><title>Foglio viaggio '+esc(x.numero_foglio_marcia||x.numero)+'</title><style>body{font-family:Arial;padding:18mm;color:#111}h1{margin:0;font-size:22px}h2{margin:5px 0 18px;font-size:16px}table{width:100%;border-collapse:collapse}th,td{border:1px solid #777;padding:7px;font-size:12px;text-align:left}th{width:32%;background:#eee}.head{margin-bottom:18px}.state{font-weight:700}@page{size:A4 portrait;margin:10mm}</style></head><body><div class="head"><h1>Croce Gialla Emergenza ODV</h1><h2>Foglio viaggio N° '+esc(x.numero_foglio_marcia||x.numero)+'</h2><div class="state">Stato: '+esc(x.stato||'APERTO')+'</div></div><table>'+
    row('N° registro',x.numero)+row('Data',x.data)+row('Tipo servizio',x.tipo_servizio)+row('Richiedente',x.richiedente_servizio)+row('N° scheda 118',x.scheda_118)+row('Paziente',[x.nome_paziente,x.cognome_paziente].filter(Boolean).join(' '))+row('Mezzo',vehicleName(x.mezzo))+row('Targa',x.targa)+row('Km iniziali',x.km_iniziali)+row('Km finali',x.km_finali)+row('Km percorsi',x.km_percorsi)+row('Ora partenza',x.ora_partenza)+row('Luogo partenza',x.luogo_partenza)+row('Ora destinazione',x.ora_destinazione)+row('Luogo carico',x.luogo_carico)+row('Tipo luogo carico',x.tipo_luogo_carico)+row('Luogo fine',x.luogo_fine)+row('Ospedale / Clinica',x.ospedale_clinica)+row('Ora fine',x.ora_fine)+row('Autista',personName(x.autista_badge))+row('Capo equipaggio',personName(x.capo_badge))+row('Soccorritore 1',personName(x.soccorritore_1_badge))+row('Soccorritore 2',personName(x.soccorritore_2_badge))+row('Metodo pagamento',x.metodo_pagamento)+row('N° ricevuta',x.numero_ricevuta)+row('Importo',money(x.importo))+row('Note',x.note)+'</table><script>window.onload=()=>window.print()<\/script></body></html>');w.document.close()
}
function buildStats(a){const km=a.reduce((s,x)=>s+(+x.km_percorsi||0),0),kmEmergenza=a.filter(x=>x.tipo_servizio==='Emergenza / Urgenza').reduce((s,x)=>s+(+x.km_percorsi||0),0),imp=a.reduce((s,x)=>s+(+x.importo||0),0);const count=f=>{const o={};a.forEach(x=>{const k=(f(x)||'Non specificato');o[k]=(o[k]||0)+1});return o};const kmPerMezzo={};a.forEach(x=>{const k=x.mezzo||'Non specificato';kmPerMezzo[k]=(kmPerMezzo[k]||0)+(+x.km_percorsi||0)});const pag={};a.forEach(x=>{const k=x.metodo_pagamento||'Non specificato';pag[k]??={viaggi:0,importo:0};pag[k].viaggi++;pag[k].importo+=(+x.importo||0)});return {viaggi:a.length,km,kmEmergenza,kmPerMezzo,importi:imp,mediaKm:a.length?km/a.length:0,schede118:a.filter(x=>x.scheda_118).length,privati:a.filter(x=>x.richiedente_servizio==='PRIVATO').length,importoMedio:a.length?imp/a.length:0,viaggiConIncasso:a.filter(x=>+x.importo>0).length,perMezzo:count(x=>x.mezzo),perTipo:count(x=>x.tipo_servizio),perRichiedente:count(x=>x.richiedente_servizio),pagamenti:pag,destinazioni:count(x=>x.luogo_fine)}}
function statsTable(obj){const r=Object.entries(obj||{}).sort((a,b)=>b[1]-a[1]);return r.length?'<table style="min-width:0"><tbody>'+r.map(x=>'<tr><td>'+esc(x[0])+'</td><td><b>'+x[1]+'</b></td></tr>').join('')+'</tbody></table>':'<div class="empty">Nessun dato</div>'}
function paymentTable(obj){const r=Object.entries(obj||{}).sort((a,b)=>b[1].importo-a[1].importo);return r.length?'<table style="min-width:0"><thead><tr><th>Metodo</th><th>Viaggi</th><th>Importo</th></tr></thead><tbody>'+r.map(x=>'<tr><td>'+esc(x[0])+'</td><td>'+x[1].viaggi+'</td><td>'+money(x[1].importo)+'</td></tr>').join('')+'</tbody></table>':'<div class="empty">Nessun dato</div>'}
function renderBars(target,a){const c=vehicles.map(v=>({name:vehicleName(v.codice),n:a.filter(x=>x.mezzo===v.codice).length})),mx=Math.max(1,...c.map(x=>x.n));$(target).innerHTML=c.map(x=>'<div class="barrow"><b>'+esc(x.name)+'</b><div class="bar"><i style="width:'+(x.n/mx*100)+'%"></i></div><span>'+x.n+' viaggi</span></div>').join('')}
function renderStats(){const ym=$('meseStatistiche').value,closed=isMonthClosed(ym),mr=monthRecord(ym);$('statoMeseStatistiche').textContent=monthStatusText(ym);let a=activeTrips().filter(x=>x.data.startsWith(ym)),s=(closed&&mr?.statistiche&&Object.keys(mr.statistiche).length)?mr.statistiche:buildStats(a);$('snapshotInfo').textContent=closed&&mr?.statistiche?'Statistiche consolidate alla chiusura del mese':'Statistiche aggiornate in tempo reale';$('sViaggi').textContent=s.viaggi||0;$('sKm').textContent=Math.round(s.km||0).toLocaleString('it-IT');$('sKmEmergenza').textContent=Math.round(s.kmEmergenza||0).toLocaleString('it-IT');$('sImporti').textContent=money(s.importi);$('sMedia').textContent=Math.round(s.mediaKm||0);$('s118').textContent=s.schede118||0;$('sPrivati').textContent=s.privati||0;$('sImportoMedio').textContent=money(s.importoMedio);$('sPagati').textContent=s.viaggiConIncasso||0;renderBars('barsStats',a);$('kmMezzoStats').innerHTML=vehicles.map(v=>'<div class="barrow"><b>'+esc(vehicleName(v.codice))+'</b><div class="bar"><i style="width:'+((Number(s.kmPerMezzo?.[v.codice]||0)/(Math.max(1,...vehicles.map(z=>Number(s.kmPerMezzo?.[z.codice]||0)))))*100)+'%"></i></div><span>'+Math.round(Number(s.kmPerMezzo?.[v.codice]||0)).toLocaleString('it-IT')+' km</span></div>').join('');$('tipoStats').innerHTML=statsTable(s.perTipo);$('richiedenteStats').innerHTML=statsTable(s.perRichiedente);$('pagamentiStats').innerHTML=paymentTable(s.pagamenti);const dest=Object.entries(s.destinazioni||{}).sort((a,b)=>b[1]-a[1]).slice(0,10);$('destStats').innerHTML=dest.length?'<table style="min-width:0"><tbody>'+dest.map(x=>'<tr><td>'+esc(x[0])+'</td><td><b>'+x[1]+'</b></td></tr>').join('')+'</tbody></table>':'<div class="empty">Nessun dato</div>';$('riepilogoStats').innerHTML='<table style="min-width:0"><tbody><tr><th>Mese</th><td>'+esc(ym)+'</td></tr><tr><th>Stato</th><td>'+(closed?'Chiuso':'Aperto')+'</td></tr><tr><th>Viaggi</th><td>'+s.viaggi+'</td></tr><tr><th>Km totali</th><td>'+Math.round(s.km||0).toLocaleString('it-IT')+'</td></tr><tr><th>Km Emergenza / Urgenza</th><td>'+Math.round(s.kmEmergenza||0).toLocaleString('it-IT')+'</td></tr>'+vehicles.map(v=>'<tr><th>Km '+esc(vehicleName(v.codice))+'</th><td>'+Math.round(Number(s.kmPerMezzo?.[v.codice]||0)).toLocaleString('it-IT')+'</td></tr>').join('')+'<tr><th>Importi</th><td>'+money(s.importi)+'</td></tr><tr><th>Schede 118</th><td>'+s.schede118+'</td></tr></tbody></table>';updateMonthAdminButton(ym,closed)}
function updateMonthAdminButton(ym,closed){const b=$('monthAdminBtn');if(!b)return;if(!isAdmin()||!ym||ym>=ymNow()){b.style.display='none';return}b.style.display='inline-block';b.textContent=closed?'Riapri mese':'Chiudi mese';b.className='btn '+(closed?'warning':'danger')}
async function toggleMonth(){if(!isAdmin())return;const ym=$('meseStatistiche').value,closed=isMonthClosed(ym);if(!ym||ym>=ymNow())return;if(!closed){const chk=monthIssues(ym);if(chk.aperti.length||chk.incompleti.length){alert('IMPOSSIBILE CHIUDERE IL MESE '+ym+'\n\nViaggi totali: '+chk.a.length+'\nFogli chiusi: '+(chk.a.length-chk.aperti.length)+'\nFogli ancora aperti: '+chk.aperti.length+'\nServizi con dati incompleti: '+chk.incompleti.length+'\n\nCompleta o chiudi i fogli indicati nella pagina Controlli.');return}}if(!confirm((closed?'Riaprire':'Chiudere')+' il mese '+ym+'?'))return;const mese=ym+'-01';let payload={mese,chiuso:!closed,updated_at:new Date().toISOString()};if(!closed){const s=buildStats(activeTrips().filter(x=>x.data.startsWith(ym)));payload.statistiche={...s,mese,generatoIl:new Date().toISOString()};payload.chiuso_at=new Date().toISOString();payload.chiuso_da=currentUser.id}else{payload.statistiche={};payload.chiuso_at=null;payload.chiuso_da=null}const {error}=await sb.from('registro_viaggi_mesi').upsert(payload,{onConflict:'mese'});if(error)return showError(error,'Gestione mese');await loadData()}
function buildAnnualStats(year){const a=activeTrips().filter(x=>(x.data||'').startsWith(String(year)+'-')),s=buildStats(a),perMese={};for(let m=1;m<=12;m++)perMese[String(m).padStart(2,'0')]=0;a.forEach(x=>{const m=x.data.slice(5,7);perMese[m]=(perMese[m]||0)+Number(x.km_percorsi||0)});return {...s,perMese}}
function renderAnnualStats(){const year=Number($('annoStatistiche').value||new Date().getFullYear()),s=buildAnnualStats(year);$('aViaggi').textContent=s.viaggi||0;$('aKm').textContent=Math.round(s.km||0).toLocaleString('it-IT');$('aKmEmergenza').textContent=Math.round(s.kmEmergenza||0).toLocaleString('it-IT');$('aImporti').textContent=money(s.importi);const maxKm=Math.max(1,...vehicles.map(v=>Number(s.kmPerMezzo?.[v.codice]||0)));$('aKmMezzo').innerHTML=vehicles.map(v=>'<div class="barrow"><b>'+esc(vehicleName(v.codice))+'</b><div class="bar"><i style="width:'+((Number(s.kmPerMezzo?.[v.codice]||0)/maxKm)*100)+'%"></i></div><span>'+Math.round(Number(s.kmPerMezzo?.[v.codice]||0)).toLocaleString('it-IT')+' km</span></div>').join('');const mesi=['Gen','Feb','Mar','Apr','Mag','Giu','Lug','Ago','Set','Ott','Nov','Dic'];$('aKmMese').innerHTML='<table style="min-width:0"><thead><tr><th>Mese</th><th>KM</th></tr></thead><tbody>'+mesi.map((n,i)=>'<tr><td>'+n+'</td><td><b>'+Math.round(Number(s.perMese[String(i+1).padStart(2,'0')]||0)).toLocaleString('it-IT')+'</b></td></tr>').join('')+'</tbody></table>'}
function renderDashboard(){const ym=ymNow(),a=activeTrips().filter(x=>x.data.startsWith(ym)),s=buildStats(a);const rest=employeeRestAnomalies(activeTrips()).filter(r=>r.precedente.data.startsWith(ym)||r.successivo.data.startsWith(ym));const ra=$('restAlert');if(ra){ra.style.display=rest.length?'block':'none';ra.innerHTML=rest.length?'<b>⚠ ATTENZIONE: possibile mancato riposo di 11 ore</b><br>'+rest.length+' anomalia'+(rest.length===1?'':'e')+' rilevata'+(rest.length===1?'':'e')+' per i dipendenti. <button class="mini" style="margin-left:8px;background:#18253a" onclick="showView(\'controlli\')">Apri Controlli</button>':''}$('kViaggi').textContent=s.viaggi;$('kKm').textContent=s.km.toLocaleString('it-IT');$('kImporti').textContent=money(s.importi);const counts=Object.entries(s.perMezzo).sort((a,b)=>b[1]-a[1]);$('kMezzo').textContent=counts[0]?vehicleName(counts[0][0]).replace('Ambulanza ',''):'–';const u=activeTrips().slice().sort((a,b)=>b.data.localeCompare(a.data)||b.numero-a.numero).slice(0,5);$('ultimi').innerHTML=u.length?'<div class="tablewrap"><table style="min-width:0"><thead><tr><th>N°</th><th>Data</th><th>Mezzo</th><th>Destinazione</th><th>Km</th></tr></thead><tbody>'+u.map(x=>'<tr><td>'+x.numero+'</td><td>'+esc(x.data)+'</td><td>'+esc(vehicleName(x.mezzo))+'</td><td>'+esc(x.luogo_fine||'')+'</td><td>'+x.km_percorsi+'</td></tr>').join('')+'</tbody></table></div>':'<div class="empty">Nessun viaggio</div>';renderBars('barsDashboard',a)}
function renderAll(){if(!currentAccess)return;renderDashboard();renderArchivio();renderStats();renderAnnualStats();renderVehicles();if($('controlliBody'))renderControlli()}
function renderVehicles(){$('vehicleGrid').innerHTML=vehicles.map(v=>'<div class="vehicle"><strong>'+esc(vehicleName(v.codice))+'</strong><span>Targa: <b>'+esc(v.targa)+'</b></span><span>Stato: attivo</span></div>').join('')}
function exportXLSX(){const a=filteredArchive();if(!a.length)return alert('Nessun viaggio da esportare.');const rows=a.map(x=>({'N°':x.numero,'N° Foglio Marcia':x.numero_foglio_marcia||'','Data':x.data,'Tipo servizio':x.tipo_servizio,'Richiedente':x.richiedente_servizio,'Scheda 118':x.scheda_118||'','Nome paziente':x.nome_paziente||'','Cognome paziente':x.cognome_paziente||'','Mezzo':vehicleName(x.mezzo),'Targa':x.targa,'Km iniziali':x.km_iniziali,'Km finali':x.km_finali,'Km percorsi':x.km_percorsi,'Ora partenza':x.ora_partenza||'','Luogo partenza':x.luogo_partenza||'','Ora destinazione':x.ora_destinazione||'','Luogo carico':x.luogo_carico||'','Tipo luogo carico':x.tipo_luogo_carico||'','Luogo fine':x.luogo_fine||'','Ospedale/Clinica':x.ospedale_clinica||'','Ora fine':x.ora_fine||'','Autista':personName(x.autista_badge),'Capo equipaggio':personName(x.capo_badge),'Soccorritore 1':personName(x.soccorritore_1_badge),'Soccorritore 2':personName(x.soccorritore_2_badge),'Metodo pagamento':x.metodo_pagamento||'','N° ricevuta':x.numero_ricevuta||'','Importo €':Number(x.importo||0),'Note':x.note||''}));const ws=XLSX.utils.json_to_sheet(rows),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Registro Viaggi');XLSX.writeFile(wb,'Registro_Viaggi_'+($('meseArchivio').value||'completo')+'.xlsx')}
function printMonth(){const a=filteredArchive(),ym=$('meseArchivio').value;if(!a.length)return alert('Nessun viaggio da stampare.');const w=window.open('','_blank');w.document.write('<!doctype html><html><head><meta charset="utf-8"><title>Registro Viaggi '+esc(ym)+'</title><style>body{font-family:Arial;padding:20px;font-size:11px}h1{margin:0}table{width:100%;border-collapse:collapse;margin-top:15px}th,td{border:1px solid #888;padding:5px;text-align:left}th{background:#eee}@page{size:A4 landscape;margin:8mm}</style></head><body><h1>Croce Gialla Emergenza ODV</h1><h2>Registro Viaggi · '+esc(ym)+'</h2><p>'+monthStatusText(ym)+' · Viaggi: '+a.length+' · Km: '+a.reduce((s,x)=>s+x.km_percorsi,0)+' · Importi: '+money(a.reduce((s,x)=>s+Number(x.importo||0),0))+'</p><table><thead><tr><th>N°</th><th>N° Foglio Marcia</th><th>Data</th><th>Servizio</th><th>Mezzo</th><th>Partenza</th><th>Carico</th><th>Fine</th><th>Km</th><th>Autista</th><th>Capo</th><th>Soccorritori</th><th>Importo</th></tr></thead><tbody>'+a.map(x=>'<tr><td>'+x.numero+'</td><td>'+esc(x.numero_foglio_marcia||'')+'</td><td>'+esc(x.data)+'</td><td>'+esc(x.tipo_servizio)+'</td><td>'+esc(vehicleName(x.mezzo))+'</td><td>'+esc(x.luogo_partenza||'')+'</td><td>'+esc(x.luogo_carico||'')+'</td><td>'+esc(x.luogo_fine||'')+'</td><td>'+x.km_percorsi+'</td><td>'+esc(personName(x.autista_badge))+'</td><td>'+esc(personName(x.capo_badge))+'</td><td>'+esc([personName(x.soccorritore_1_badge),personName(x.soccorritore_2_badge)].filter(Boolean).join(', '))+'</td><td>'+money(x.importo)+'</td></tr>').join('')+'</tbody></table><script>window.onload=()=>window.print()<\/script></body></html>');w.document.close()}
function auditLabel(x){const p=x.prima||{},d=x.dopo||{};if(x.azione==='INSERT')return 'CREATO';if(x.azione==='DELETE')return 'ELIMINATO';if(!p.eliminato_at&&d.eliminato_at)return 'SPOSTATO NEL CESTINO';if(p.eliminato_at&&!d.eliminato_at)return 'RIPRISTINATO';if(p.stato==='APERTO'&&d.stato==='CHIUSO')return 'FOGLIO CHIUSO';if(p.stato==='CHIUSO'&&d.stato==='APERTO')return 'FOGLIO RIAPERTO';return 'MODIFICATO'}
async function loadAdminTools(){if(!isAdmin())return;const [b,d,a]=await Promise.all([sb.from('registro_viaggi_backup').select('id,creato_il,tipo').order('creato_il',{ascending:false}).limit(10),sb.from('registro_viaggi').select('id,numero,data,tipo_servizio,eliminato_at').not('eliminato_at','is',null).order('eliminato_at',{ascending:false}).limit(30),sb.from('registro_viaggi_audit').select('id,viaggio_id,azione,actor_user_id,avvenuto_il,prima,dopo').order('avvenuto_il',{ascending:false}).limit(30)]);if(b.error||d.error||a.error)return showError(b.error||d.error||a.error,'Strumenti amministrazione');$('backupList').innerHTML=(b.data||[]).length?(b.data||[]).map(x=>'<div class="box" style="margin:6px 0"><b>'+esc(x.tipo)+'</b> · '+new Date(x.creato_il).toLocaleString('it-IT')+'</div>').join(''):'<div class="empty">Nessun backup automatico ancora disponibile.</div>';$('trashList').innerHTML=(d.data||[]).length?(d.data||[]).map(x=>'<div class="box" style="margin:6px 0">N° <b>'+x.numero+'</b> · '+esc(x.data)+' · '+esc(x.tipo_servizio)+' <button class="mini" style="background:#2c9a62;float:right" onclick="restoreTrip(\''+x.id+'\')">Ripristina</button></div>').join(''):'<div class="empty">Cestino vuoto.</div>';$('auditList').innerHTML=(a.data||[]).length?(a.data||[]).map(x=>{const num=x.dopo?.numero||x.prima?.numero||'–',who=x.actor_user_id===currentUser?.id?(currentAccess?.nome||'Utente corrente'):String(x.actor_user_id||'Sistema').slice(0,8);return '<div class="box" style="margin:6px 0"><b>'+esc(auditLabel(x))+'</b> · viaggio N° '+esc(num)+' · '+new Date(x.avvenuto_il).toLocaleString('it-IT')+' · '+esc(who)+'</div>'}).join(''):'<div class="empty">Nessuna attività.</div>'}
async function restoreTrip(id){if(!isAdmin())return;if(!confirm('Ripristinare questo viaggio?'))return;const {error}=await sb.from('registro_viaggi').update({eliminato_at:null,eliminato_da:null}).eq('id',id);if(error)return showError(error,'Ripristino');await loadData();await loadAdminTools()}
async function downloadBackup(){if(!isAdmin())return;const [t,m]=await Promise.all([sb.from('registro_viaggi').select('*').order('numero'),sb.from('registro_viaggi_mesi').select('*').order('mese')]);if(t.error||m.error)return showError(t.error||m.error,'Backup');const blob=new Blob([JSON.stringify({creatoIl:new Date().toISOString(),viaggi:t.data,mesi:m.data},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='backup_registro_viaggi_'+iso(new Date())+'.json';a.click();URL.revokeObjectURL(url)}
document.addEventListener('DOMContentLoaded',()=>{$('loginForm').addEventListener('submit',login);$('logoutBtn').addEventListener('click',logout);const ym=ymNow();$('meseArchivio').value=ym;$('meseStatistiche').value=ym;if($('meseControlli'))$('meseControlli').value=ym;$('annoStatistiche').value=new Date().getFullYear();$('meseArchivio').addEventListener('change',renderArchivio);$('meseStatistiche').addEventListener('change',renderStats);if($('meseControlli'))$('meseControlli').addEventListener('change',renderControlli);$('annoStatistiche').addEventListener('change',renderAnnualStats);bootstrap()});
